### ISSUE TITLE
Revised by?

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Edison_ADC_Block#2]
Do we want a revised by element added to the SCH and BRD for this design?

if not, disregard.

**Comment by ToniCorinne** [comment]
Since Mike's name is on for the original designer, and Casey is doing the rev, I'd say please add that. Helps with record keeping as to who has touched it last.

**Comment by caseykuhns** [comment]
fixed

**Comment by caseykuhns** [comment]
Or use github? to see who touched it last?

**Comment by ToniCorinne** [comment]
If the files are accessed from a zip, the Git history isn't there.
