### ISSUE TITLE
Copper Pour Isolate

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Edison_ADC_Block#5]
Currently set to 2mil instead of 12mil. 

if this is intentional, disregard.

**Comment by caseykuhns** [comment]
fixed

**Comment by ericorosel** [comment]
Looks like the isolate got set to 1.2mil instead of 12mil

**Comment by caseykuhns** [comment]
Ok, I looked at other blocks and it looks like 2mil isolate is the norm.  We have 6mill spacing set by the DRU.  The 2mil allows the GND to connect to the edison connectors, without it, it gets ugly fast.

**Comment by ericorosel** [comment]
Sounds good, thanks
