### ISSUE TITLE
Component names and values

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Edison_ADC_Block#6]
PCA needs Tname and Tvalue in BRD

Hirose needs Tname and Tvalue in BRD

MIC VREG needs value in SCH

**Comment by caseykuhns** [comment]
PCA done
MIC Done
Hirose may need some work.

**Comment by caseykuhns** [comment]
Dug into the Hirose, one connector is named for the Edison (it's a module connection, not a simple connector, the other is a connector.  I'll try to add product id's to each.  Names and values might be tough

**Comment by caseykuhns** [comment]
added values
