### ISSUE TITLE
ADC Block V20 Proto Checklist #2 Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Edison_ADC_Block#7]
(1) Looks like there is a mix and match of different sized traces around the PCA (some .01" and some .006"). The .006" traces going to the Hirose are okay, but I think we could go up to .01" on some of the smaller traces that do not lead to the Hirose. 

As of now I think functionality should be fine, but for consistency, it may be worth changing some of the trace sizes; up to you.

(2) Can you add a line/polygon of "Trestrict" to the side of the GND pad on the PCA to get rid of the GND hash mark on the side of the pad. (Between SDA1 and GND)

(3) The measurement graphics are on "TDocu" instead of the "Measures" layer; up to you.

**Comment by caseykuhns** [comment]
1) I fixed all trace widths to be .01" the .06 are connecting the hirose connectors
2) added the T restrict
3) Moved dimensions to Measures layer.
